name: kmart_retail
version: 1.0.0
config-version: 2
profile: kmart_retail

dbt-cloud:
  project-id: 70506183158510

model-paths: [models]
test-paths: [tests]
macro-paths: [macros]
seed-paths: [seeds]
clean-targets: [target, dbt_packages]

models:
  kmart_retail:
    +materialized: view
    staging:
      +schema: staging
      +tags: [bronze]
    intermediate:
      +schema: intermediate
      +materialized: table
      +tags: [silver]
    marts:
      +schema: gold
      +materialized: table
      +tags: [gold]
